%=== Data Set path and image library ====================================== 
datasetpathTrain='INSERT_PATH_TO_IMAGE_TRAINING_DATABASE';
datasetpathTest='INSERT_PATH_TO_IMAGE_TESTING_DATABASE';
datasetpathValidation='INSERT_PATH_TO_IMAGE_Validation_DATABASE';
imdsTrain = imageDatastore(datasetpathTrain, ...
            'IncludeSubfolders',true, ...
            'LabelSource','foldernames');
imdsValidation = imageDatastore(datasetpathValidation, ...
                'IncludeSubfolders',true, ...
                'LabelSource','foldernames');
imdsTest = imageDatastore(datasetpathTest, ...
           'IncludeSubfolders',true, ...
           'LabelSource','foldernames');
%=== Label counter ========================================================
labelCountTrain = countEachLabel(imdsTrain);
labelCountValidation = countEachLabel(imdsValidation);
labelCountTest = countEachLabel(imdsTest);

%=== Check image size =====================================================
img = readimage(imdsTrain,1);
imdsTrainSize = size(img);

%=== Training options for the CNN =========================================
options = trainingOptions('adam', ...
    'GradientDecayFactor',0.99,...
    'SquaredGradientDecayFactor',0.99,...
    'MaxEpochs',25, ...
    'Shuffle','every-epoch', ...
    'MiniBatchSize',64,...
    'ValidationData',imdsValidation, ...
    'ValidationFrequency',20, ...
    'Verbose', true, ...
    'VerboseFrequency', 20, ...
    'Plots','training-progress',...
    'ExecutionEnvironment', 'parallel');
%=== Training layers for the CNN ==========================================
   layers = [...
    imageInputLayer([imdsTrainSize 1],'Name','InputLayer')
    convolution2dLayer(12,16,'Stride',4,'Name','ConvolutionLayer')
    reluLayer('Name','ReLULayer')
    maxPooling2dLayer(2,'Stride',4,'Name','PoolingLayer')
    fullyConnectedLayer(6,'Name','FullyConnectedLayer')
    softmaxLayer('Name','SoftmaxLayer')
    classificationLayer('Name','ClassificationLayer')
    ];
%=== Network training =====================================================
net = trainNetwork(imdsTrain,layers,options);

%=== Test the classifing with the test data set and measure accuracy ======
YPred = classify(net,imdsTest);
YValidation = imdsTest.Labels;
confMatDL = confusionmat(YValidation,YPred);

%=== Save results for further use =========================================
save('DeepLearnSim')